import type { Metadata } from "next";
import { Alata, Raleway, Cherish } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-raleway",
})

const alata = Alata({
  display: "swap",
  weight: "400",
  variable: "--font-alata",
})

const cherish = Cherish({
  display: "swap",
  weight: "400",
  variable: "--font-cherish",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${alata.variable} ${cherish.variable} ${raleway.variable}`}>
      <body>
        <div className="theme-bg items-center min-h-screen min-w-screen h-auto w-auto pl-10 pr-10 pt-5 relative">
            {children}
        </div>
        
      </body>
    </html>
  );
}
