import type { Metadata } from "next";
import { Alata, Raleway, Cherish } from "next/font/google";
import "./globals.css";
import Menu from "./Menu";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-raleway",
})

const alata = Alata({
  display: "swap",
  weight: "400",
  variable: "--font-alata",
})

const cherish = Cherish({
  display: "swap",
  weight: "400",
  variable: "--font-cherish",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${alata.variable} ${cherish.variable} ${raleway.variable}`}>
      <body>
        <div className="theme-bg items-center h-screen w-screen pl-10 pr-10 pt-5 relative">
          <header className="justify-between flex flex-row items-center text-white"> {/* header */}
            <div className="justify-start">
              <h1 className={`alata text-moon-yellow text-[80px]`}>AILUN SHI</h1>
            </div>

            <div className="justify-end"> {/* menu */}
              <Menu />
            </div>

          </header>

          <div className="flex flex-row items-center justify-between p-5 mb-10"> {/* need to make sure it adjusts with window size*/}
            <Image
              className="justify-start -m-30"
              src="/line.svg"
              alt="Golden line on left side"
              width={500}
              height={100}
              priority
            />

            <h2 className={`cherish text-[120px] -m-20`}>
              about {/* replace this with child */}
            </h2>

            <Image
              className="justify-end -m-30"
              src="/line.svg"
              alt="Golden line on left side"
              width={500}
              height={100}
              priority
            />
          </div>

          { children }

        </div>

      </body>
    </html>
  );
}
